// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-10-06T19:11:40+07:00

package model

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Role struct {
	  ID       int64   `json:"id"`
	  Name       string   `json:"name"`
	  Description       sql.NullString   `json:"description"`
	  Privileges       string   `json:"privileges"`
}

type RoleField string

const (
	RoleField_ID       RoleField = "id"
	RoleField_Name       RoleField = "name"
	RoleField_Description       RoleField = "description"
	RoleField_Privileges       RoleField = "privileges"
	
)

type RoleSorting struct {
	Field RoleField  `json:"field"`
	Dir   SortDir         `json:"dir"`
}

type RoleFilter struct {
	Field RoleField  `json:"field"`
	Op    FilterOp   `json:"op"`
	Value json.RawMessage `json:"value"`
}

