// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-09-24T17:04:14+07:00

package model

import (
	"database/sql"
	"encoding/json"
	"time"
)

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Version   int64          `json:"version"`
	Name      string         `json:"name"`
	Salt      string         `json:"salt"`
	Password  string         `json:"password"`
	Token     sql.NullString `json:"token"`
	Roles     []Role         `json:"roles"`
	CreatedBy *User          `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedBy *User          `json:"updated_by"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type UserField string

const (
	UserField_ID        UserField = "id"
	UserField_Email     UserField = "email"
	UserField_Version   UserField = "version"
	UserField_Name      UserField = "name"
	UserField_Salt      UserField = "salt"
	UserField_Password  UserField = "password"
	UserField_Token     UserField = "token"
	UserField_Roles     UserField = "roles"
	UserField_CreatedBy UserField = "created_by"
	UserField_CreatedAt UserField = "created_at"
	UserField_UpdatedBy UserField = "updated_by"
	UserField_UpdatedAt UserField = "updated_at"
)

type UserSort struct {
	Field UserField `json:"field"`
	Dir   SortDir   `json:"dir"`
}

type UserFilter struct {
	Field UserField       `json:"field"`
	Op    FilterOp        `json:"op"`
	Value json.RawMessage `json:"value"`
}
