// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-09-30T09:47:33+07:00

package model

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
)

func (r *StoreImpl) User() UserStore {
	return &UserStoreImpl{
		StoreImpl: r,
	}
}

type UserStore interface {
	Create(ctx context.Context, obj User) (*User, error)
	Get(ctx context.Context, id int64) (*User, error)
	GetByName(ctx context.Context, name string) (*User, error)
	FindOne(ctx context.Context, filter []UserFilter, sorting []UserSorting) (*User, error)
	Find(ctx context.Context, filter []UserFilter, sorting []UserSorting, limit int, offset int64) ([]User, int64, error)
	Update(ctx context.Context, obj User, fields []UserField) error
	Delete(ctx context.Context, id int64) error
}

type UserStoreImpl struct {
	*StoreImpl
}

func (r *UserStoreImpl) Create(ctx context.Context, obj User) (*User, error) {
	var tx *sql.Tx
	var err error
	var txNew bool
	tx, err = r.db.BeginTx(ctx, nil)
	txNew = true
	defer tx.Rollback()
	obj.Version = 1
	var objCreatedBy_ID sql.NullInt64
	if obj.CreatedBy != nil {
		objCreatedBy_ID = sql.NullInt64{Int64: obj.CreatedBy.ID, Valid: true}
	} else {
		objCreatedBy_ID = sql.NullInt64{Valid: false}
	}
	var objUpdatedBy_ID sql.NullInt64
	if obj.UpdatedBy != nil {
		objUpdatedBy_ID = sql.NullInt64{Int64: obj.UpdatedBy.ID, Valid: true}
	} else {
		objUpdatedBy_ID = sql.NullInt64{Valid: false}
	}
	qry := `
    INSERT INTO app_user (
      email,
      version,
      name,
      salt,
      password,
      token,
      created_by,
      created_at,
      updated_by,
      updated_at
    ) VALUES (
      $1,
      $2,
      $3,
      $4,
      $5,
      $6,
      $7,
      $8,
      $9,
      $10
    )`
	res, err := tx.ExecContext(ctx, qry,
		obj.Email,
		obj.Version,
		obj.Name,
		obj.Salt,
		obj.Password,
		obj.Token,
		objCreatedBy_ID,
		obj.CreatedAt,
		objUpdatedBy_ID,
		obj.UpdatedAt,
	)
	if err != nil {
		slog.Error("Insert", "qry:", qry, "Error:", err)
		return nil, err
	}
	ra, err := res.RowsAffected()
	if err != nil {
		return nil, err
	}
	if ra != 1 {
		return nil, fmt.Errorf("ERR_INSERT_FAILED")
	}
	obj.ID, err = res.LastInsertId()
	if err != nil {
		return nil, err
	}
	qry = `
    INSERT INTO app_user_role (app_user, app_role)
    VALUES (
        $1, 
        $2)`
	for _, objRef := range obj.Roles {
		res, err := tx.ExecContext(ctx, qry, obj.ID, objRef.ID)
		if err != nil {
			slog.Error("Insert app_user_role", "qry:", qry, "Error:", err)
			return nil, err
		}
		ra, err := res.RowsAffected()
		if err != nil {
			return nil, err
		}
		if ra != 1 {
			return nil, fmt.Errorf("ERR_INSERT_FAILED")
		}
	}
	if txNew {
		err = tx.Commit()
		if err != nil {
			return nil, err
		}
	}
	return &obj, nil
}

func (r *UserStoreImpl) Get(ctx context.Context, id int64) (*User, error) {
	qry := `
    SELECT
      obj.id,
      obj.email,
      obj.version,
      obj.name,
      obj.salt,
      obj.password,
      obj.token,
      objRoles_ref.id,
      objRoles_ref.name,
      objCreatedBy.id,
      objCreatedBy.name,
      objCreatedBy.email,
      obj.created_at,
      objUpdatedBy.id,
      objUpdatedBy.name,
      objUpdatedBy.email,
      obj.updated_at
    FROM
      ((((app_user obj LEFT JOIN app_user_role objRoles ON obj.id = objRoles.app_user)
      LEFT JOIN app_role objRoles_ref ON objRoles_ref.id = objRoles.app_role)
      LEFT JOIN app_user objCreatedBy ON obj.created_by = objCreatedBy.id)
      LEFT JOIN app_user objUpdatedBy ON obj.updated_by = objUpdatedBy.id)
    WHERE
      obj.id = $1`
	var obj User
	var refRoles *Role
	var refRoles_ID sql.NullInt64
	var refRoles_Name sql.NullString
	var refCreatedBy_ID sql.NullInt64
	var refCreatedBy_Name sql.NullString
	var refCreatedBy_Email sql.NullString
	var refUpdatedBy_ID sql.NullInt64
	var refUpdatedBy_Name sql.NullString
	var refUpdatedBy_Email sql.NullString
	rows, err := r.db.QueryContext(ctx, qry, id)
	if err != nil {
		slog.Error("Query", "qry:", qry, "Error:", err)
		return nil, err
	}
	if rows.Next() {
		err = rows.Scan(
			&obj.ID,
			&obj.Email,
			&obj.Version,
			&obj.Name,
			&obj.Salt,
			&obj.Password,
			&obj.Token,
			&refRoles_ID,
			&refRoles_Name,
			&refCreatedBy_ID,
			&refCreatedBy_Name,
			&refCreatedBy_Email,
			&obj.CreatedAt,
			&refUpdatedBy_ID,
			&refUpdatedBy_Name,
			&refUpdatedBy_Email,
			&obj.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}
		if refCreatedBy_ID.Valid {
			if obj.CreatedBy == nil {
				obj.CreatedBy = &User{ID: refCreatedBy_ID.Int64}
			} else {
				obj.CreatedBy.ID = refCreatedBy_ID.Int64
			}
		}
		if refCreatedBy_Name.Valid {
			obj.CreatedBy.Name = refCreatedBy_Name.String
		}
		if refCreatedBy_Email.Valid {
			obj.CreatedBy.Email = refCreatedBy_Email.String
		}
		if refUpdatedBy_ID.Valid {
			if obj.UpdatedBy == nil {
				obj.UpdatedBy = &User{ID: refUpdatedBy_ID.Int64}
			} else {
				obj.UpdatedBy.ID = refUpdatedBy_ID.Int64
			}
		}
		if refUpdatedBy_Name.Valid {
			obj.UpdatedBy.Name = refUpdatedBy_Name.String
		}
		if refUpdatedBy_Email.Valid {
			obj.UpdatedBy.Email = refUpdatedBy_Email.String
		}

		if refRoles_ID.Valid {
			refRoles = &Role{ID: refRoles_ID.Int64}
		}
		if refRoles != nil && refRoles_Name.Valid {
			refRoles.Name = refRoles_Name.String
		}
		if refRoles != nil {
			obj.Roles = append(obj.Roles, *refRoles)
			refRoles = nil
		}
		for rows.Next() {
			err = rows.Scan(
				&obj.ID,
				&obj.Email,
				&obj.Version,
				&obj.Name,
				&obj.Salt,
				&obj.Password,
				&obj.Token,
				&refRoles_ID,
				&refRoles_Name,
				&refCreatedBy_ID,
				&refCreatedBy_Name,
				&refCreatedBy_Email,
				&obj.CreatedAt,
				&refUpdatedBy_ID,
				&refUpdatedBy_Name,
				&refUpdatedBy_Email,
				&obj.UpdatedAt,
			)
			if err != nil {
				return nil, err
			}

			if refRoles_ID.Valid {
				refRoles = &Role{ID: refRoles_ID.Int64}
			}
			if refRoles != nil && refRoles_Name.Valid {
				refRoles.Name = refRoles_Name.String
			}
			if refRoles != nil {
				obj.Roles = append(obj.Roles, *refRoles)
				refRoles = nil
			}
		}
	}
	return &obj, nil
}

func (r *UserStoreImpl) GetByName(ctx context.Context, name string) (*User, error) {
	qry := `
    SELECT
      obj.id,
      obj.email,
      obj.version,
      obj.name,
      obj.salt,
      obj.password,
      obj.token,
      objRoles_ref.id,
      objRoles_ref.name,
      objCreatedBy.id,
      objCreatedBy.name,
      objCreatedBy.email,
      obj.created_at,
      objUpdatedBy.id,
      objUpdatedBy.name,
      objUpdatedBy.email,
      obj.updated_at
    FROM
      ((((app_user obj LEFT JOIN app_user_role objRoles ON obj.id = objRoles.app_user)
      LEFT JOIN app_role objRoles_ref ON objRoles_ref.id = objRoles.app_role)
      LEFT JOIN app_user objCreatedBy ON obj.created_by = objCreatedBy.id)
      LEFT JOIN app_user objUpdatedBy ON obj.updated_by = objUpdatedBy.id)
    WHERE
      obj.name = $1`
	var obj User
	var refRoles *Role
	var refRoles_ID sql.NullInt64
	var refRoles_Name sql.NullString
	var refCreatedBy_ID sql.NullInt64
	var refCreatedBy_Name sql.NullString
	var refCreatedBy_Email sql.NullString
	var refUpdatedBy_ID sql.NullInt64
	var refUpdatedBy_Name sql.NullString
	var refUpdatedBy_Email sql.NullString
	rows, err := r.db.QueryContext(ctx, qry, name)
	if err != nil {
		return nil, err
	}
	if refCreatedBy_ID.Valid {
		if obj.CreatedBy == nil {
			obj.CreatedBy = &User{ID: refCreatedBy_ID.Int64}
		} else {
			obj.CreatedBy.ID = refCreatedBy_ID.Int64
		}
	}
	if refCreatedBy_Name.Valid {
		obj.CreatedBy.Name = refCreatedBy_Name.String
	}
	if refCreatedBy_Email.Valid {
		obj.CreatedBy.Email = refCreatedBy_Email.String
	}
	if refUpdatedBy_ID.Valid {
		if obj.UpdatedBy == nil {
			obj.UpdatedBy = &User{ID: refUpdatedBy_ID.Int64}
		} else {
			obj.UpdatedBy.ID = refUpdatedBy_ID.Int64
		}
	}
	if refUpdatedBy_Name.Valid {
		obj.UpdatedBy.Name = refUpdatedBy_Name.String
	}
	if refUpdatedBy_Email.Valid {
		obj.UpdatedBy.Email = refUpdatedBy_Email.String
	}

	if refRoles_ID.Valid {
		refRoles = &Role{ID: refRoles_ID.Int64}
	}
	if refRoles != nil && refRoles_Name.Valid {
		refRoles.Name = refRoles_Name.String
	}
	if refRoles != nil {
		obj.Roles = append(obj.Roles, *refRoles)
		refRoles = nil
	}
	for rows.Next() {
		err = rows.Scan(
			&obj.ID,
			&obj.Email,
			&obj.Version,
			&obj.Name,
			&obj.Salt,
			&obj.Password,
			&obj.Token,
			&refRoles_ID,
			&refRoles_Name,
			&refCreatedBy_ID,
			&refCreatedBy_Name,
			&refCreatedBy_Email,
			&obj.CreatedAt,
			&refUpdatedBy_ID,
			&refUpdatedBy_Name,
			&refUpdatedBy_Email,
			&obj.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}

		if refRoles_ID.Valid {
			refRoles = &Role{ID: refRoles_ID.Int64}
		}
		if refRoles != nil && refRoles_Name.Valid {
			refRoles.Name = refRoles_Name.String
		}
		if refRoles != nil {
			obj.Roles = append(obj.Roles, *refRoles)
			refRoles = nil
		}
	}
	return &obj, nil
}

func (r *UserStoreImpl) FindOne(ctx context.Context, filter []UserFilter, sorting []UserSorting) (*User, error) {
	qfilter := []string{}
	args := []any{}
	for _, f := range filter {
		switch f.Field {
		case UserField_Email:
			switch f.Op {
			case FilterOp_EQ:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.email = $%d", len(args)))
			case FilterOp_Like:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.email LIKE $%d", len(args)))
			case FilterOp_ILike:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.email ILIKE $%d", len(args)))
			default:
				return nil, fmt.Errorf("unsupported filter op %v for field %v", f.Op, f.Field)
			}
		case UserField_Name:
			switch f.Op {
			case FilterOp_EQ:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.name = $%d", len(args)))
			case FilterOp_Like:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.name LIKE $%d", len(args)))
			case FilterOp_ILike:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.name ILIKE $%d", len(args)))
			default:
				return nil, fmt.Errorf("unsupported filter op %v for field %v", f.Op, f.Field)
			}
		default:
			return nil, fmt.Errorf("unsupported filter field %v", f.Field)
		}
	}
	qry := `
    SELECT
      obj.id,
      obj.email,
      obj.version,
      obj.name,
      obj.salt,
      obj.password,
      obj.token,
      objCreatedBy.id,
      objCreatedBy.name,
      objCreatedBy.email,
      obj.created_at,
      objUpdatedBy.id,
      objUpdatedBy.name,
      objUpdatedBy.email,
      obj.updated_at
    FROM
      ((app_user obj LEFT JOIN app_user objCreatedBy ON obj.created_by = objCreatedBy.id)
      LEFT JOIN app_user objUpdatedBy ON obj.updated_by = objUpdatedBy.id)`
	if len(qfilter) > 0 {
		qry += "\n  WHERE " + strings.Join(qfilter, " AND\n    ")
	}
	if len(sorting) > 0 {
		sorts := []string{}
		for _, f := range sorting {
			switch f.Field {
			case UserField_Email:
				if f.Dir == SortDir_ASC {
					sorts = append(sorts, "obj.email ASC")
				} else {
					sorts = append(sorts, "obj.email DESC")
				}
			case UserField_Name:
				if f.Dir == SortDir_ASC {
					sorts = append(sorts, "obj.name ASC")
				} else {
					sorts = append(sorts, "obj.name DESC")
				}
			}
		}
		if len(sorts) > 0 {
			qry += "\n  ORDER BY " + strings.Join(sorts, ", ")
		}
	}
	qry += "\n  LIMIT 1"
	rows, err := r.db.QueryContext(ctx, qry, args...)
	if err != nil {
		slog.Error("Query list", "qry:", qry, "Error:", err)
		return nil, err
	}
	if rows.Next() {
		var obj User
		var refCreatedBy_ID sql.NullInt64
		var refCreatedBy_Name sql.NullString
		var refCreatedBy_Email sql.NullString
		var refUpdatedBy_ID sql.NullInt64
		var refUpdatedBy_Name sql.NullString
		var refUpdatedBy_Email sql.NullString
		err = rows.Scan(
			&obj.ID,
			&obj.Email,
			&obj.Version,
			&obj.Name,
			&obj.Salt,
			&obj.Password,
			&obj.Token,
			&refCreatedBy_ID,
			&refCreatedBy_Name,
			&refCreatedBy_Email,
			&obj.CreatedAt,
			&refUpdatedBy_ID,
			&refUpdatedBy_Name,
			&refUpdatedBy_Email,
			&obj.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}
		if refCreatedBy_ID.Valid {
			if obj.CreatedBy == nil {
				obj.CreatedBy = &User{ID: refCreatedBy_ID.Int64}
			} else {
				obj.CreatedBy.ID = refCreatedBy_ID.Int64
			}
		}
		if refCreatedBy_Name.Valid {
			obj.CreatedBy.Name = refCreatedBy_Name.String
		}
		if refCreatedBy_Email.Valid {
			obj.CreatedBy.Email = refCreatedBy_Email.String
		}
		if refUpdatedBy_ID.Valid {
			if obj.UpdatedBy == nil {
				obj.UpdatedBy = &User{ID: refUpdatedBy_ID.Int64}
			} else {
				obj.UpdatedBy.ID = refUpdatedBy_ID.Int64
			}
		}
		if refUpdatedBy_Name.Valid {
			obj.UpdatedBy.Name = refUpdatedBy_Name.String
		}
		if refUpdatedBy_Email.Valid {
			obj.UpdatedBy.Email = refUpdatedBy_Email.String
		}
		return &obj, nil
	}
	return nil, fmt.Errorf("not found")
}

func (r *UserStoreImpl) Find(ctx context.Context, filter []UserFilter, sorting []UserSorting, limit int, offset int64) ([]User, int64, error) {
	qfilter := []string{}
	args := []any{}
	for _, f := range filter {
		switch f.Field {
		case UserField_Email:
			switch f.Op {
			case FilterOp_EQ:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, 0, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.email = $%d", len(args)))
			case FilterOp_Like:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, 0, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.email LIKE $%d", len(args)))
			case FilterOp_ILike:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, 0, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.email ILIKE $%d", len(args)))
			default:
				return nil, 0, fmt.Errorf("unsupported filter op %v for field %v", f.Op, f.Field)
			}
		case UserField_Name:
			switch f.Op {
			case FilterOp_EQ:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, 0, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.name = $%d", len(args)))
			case FilterOp_Like:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, 0, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.name LIKE $%d", len(args)))
			case FilterOp_ILike:
				var val string
				err := json.Unmarshal(f.Value, &val)
				if err != nil {
					return nil, 0, err
				}
				args = append(args, val)
				qfilter = append(qfilter, fmt.Sprintf("obj.name ILIKE $%d", len(args)))
			default:
				return nil, 0, fmt.Errorf("unsupported filter op %v for field %v", f.Op, f.Field)
			}
		default:
			return nil, 0, fmt.Errorf("unsupported filter field %v", f.Field)
		}
	}
	qry := `SELECT COUNT(obj.id) FROM app_user obj`
	if len(qfilter) > 0 {
		qry += " WHERE " + strings.Join(qfilter, " AND ")
	}
	total := int64(0)
	err := r.db.QueryRowContext(ctx, qry, args...).Scan(&total)
	if err != nil {
		slog.Error("Query count", "qry:", qry, "Error:", err)
		return nil, 0, err
	}
	qry = `SELECT
      obj.id,
      obj.email,
      obj.version,
      obj.name,
      obj.salt,
      obj.password,
      obj.token,
      objCreatedBy.id,
      objCreatedBy.name,
      objCreatedBy.email,
      obj.created_at,
      objUpdatedBy.id,
      objUpdatedBy.name,
      objUpdatedBy.email,
      obj.updated_at
    FROM
      ((app_user obj LEFT JOIN app_user objCreatedBy ON obj.created_by = objCreatedBy.id)
      LEFT JOIN app_user objUpdatedBy ON obj.updated_by = objUpdatedBy.id)`
	if len(qfilter) > 0 {
		qry += "\n  WHERE " + strings.Join(qfilter, " AND\n    ")
	}
	if len(sorting) > 0 {
		sorts := []string{}
		for _, f := range sorting {
			switch f.Field {
			case UserField_Email:
				if f.Dir == SortDir_ASC {
					sorts = append(sorts, "obj.email ASC")
				} else {
					sorts = append(sorts, "obj.email DESC")
				}
			case UserField_Name:
				if f.Dir == SortDir_ASC {
					sorts = append(sorts, "obj.name ASC")
				} else {
					sorts = append(sorts, "obj.name DESC")
				}
			}
		}
		if len(sorts) > 0 {
			qry += "\n  ORDER BY " + strings.Join(sorts, ", ")
		}
	}
	qry += fmt.Sprintf("\n  LIMIT %d OFFSET %d", limit, offset)
	rows, err := r.db.QueryContext(ctx, qry, args...)
	if err != nil {
		slog.Error("Query list", "qry:", qry, "Error:", err)
		return nil, 0, err
	}
	list := []User{}
	for rows.Next() {
		var obj User
		var refCreatedBy_ID sql.NullInt64
		var refCreatedBy_Name sql.NullString
		var refCreatedBy_Email sql.NullString
		var refUpdatedBy_ID sql.NullInt64
		var refUpdatedBy_Name sql.NullString
		var refUpdatedBy_Email sql.NullString
		err = rows.Scan(
			&obj.ID,
			&obj.Email,
			&obj.Version,
			&obj.Name,
			&obj.Salt,
			&obj.Password,
			&obj.Token,
			&refCreatedBy_ID,
			&refCreatedBy_Name,
			&refCreatedBy_Email,
			&obj.CreatedAt,
			&refUpdatedBy_ID,
			&refUpdatedBy_Name,
			&refUpdatedBy_Email,
			&obj.UpdatedAt,
		)
		if err != nil {
			return nil, total, err
		}
		if refCreatedBy_ID.Valid {
			if obj.CreatedBy == nil {
				obj.CreatedBy = &User{ID: refCreatedBy_ID.Int64}
			} else {
				obj.CreatedBy.ID = refCreatedBy_ID.Int64
			}
		}
		if refCreatedBy_Name.Valid {
			obj.CreatedBy.Name = refCreatedBy_Name.String
		}
		if refCreatedBy_Email.Valid {
			obj.CreatedBy.Email = refCreatedBy_Email.String
		}
		if refUpdatedBy_ID.Valid {
			if obj.UpdatedBy == nil {
				obj.UpdatedBy = &User{ID: refUpdatedBy_ID.Int64}
			} else {
				obj.UpdatedBy.ID = refUpdatedBy_ID.Int64
			}
		}
		if refUpdatedBy_Name.Valid {
			obj.UpdatedBy.Name = refUpdatedBy_Name.String
		}
		if refUpdatedBy_Email.Valid {
			obj.UpdatedBy.Email = refUpdatedBy_Email.String
		}
		list = append(list, obj)
	}
	return list, total, nil
}

func (r *UserStoreImpl) Update(ctx context.Context, obj User, fields []UserField) error {
	var tx *sql.Tx
	var err error
	var txNew bool
	tx, err = r.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	txNew = true
	defer tx.Rollback()
	args := []any{}
	qry := `UPDATE app_user SET`
	if len(args) > 0 {
		qry += ","
	}
	args = append(args, obj.Version+1)
	qry += fmt.Sprintf("  version = $%d", len(args))
	for _, f := range fields {
		switch f {
		case UserField_Email:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Email)
			qry += fmt.Sprintf("  email = $%d", len(args))
		case UserField_Name:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Name)
			qry += fmt.Sprintf("  name = $%d", len(args))
		case UserField_Token:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Token)
			qry += fmt.Sprintf("  token = $%d", len(args))
		case UserField_Roles:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Roles)
			qry += fmt.Sprintf("  roles = $%d", len(args))
		case UserField_CreatedBy:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.CreatedBy)
			qry += fmt.Sprintf("  created_by = $%d", len(args))
		case UserField_CreatedAt:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.CreatedAt)
			qry += fmt.Sprintf("  created_at = $%d", len(args))
		case UserField_UpdatedBy:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.UpdatedBy)
			qry += fmt.Sprintf("  updated_by = $%d", len(args))
		case UserField_UpdatedAt:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.UpdatedAt)
			qry += fmt.Sprintf("  updated_at = $%d", len(args))
		default:
			return fmt.Errorf("field %v is unknown", f)
		}
	}
	qry += "\nWHERE\n"
	args = append(args, obj.ID)
	qry += fmt.Sprintf("  id = $%d", len(args))
	args = append(args, obj.Version)
	qry += fmt.Sprintf(" AND\n  version = $%d", len(args))
	res, err := tx.ExecContext(ctx, qry, args...)
	if err != nil {
		slog.Error("Update", "qry:", qry, "Error:", err)
		return err
	}
	ra, err := res.RowsAffected()
	if err != nil {
		slog.Error("Update", "qry:", qry, "args:", args, "Error:", err)
		return err
	}
	if ra == 0 {
		return fmt.Errorf("no rows affected")
	}
	if ra != 1 {
		return fmt.Errorf("invalid rows affected (%d)", ra)
	}
	if txNew {
		err = tx.Commit()
		if err != nil {
			return err
		}
	}
	return nil
}

func (r *UserStoreImpl) Delete(ctx context.Context, id int64) error {
	var tx *sql.Tx
	var err error
	var txNew bool
	tx, err = r.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	txNew = true
	qry := `
    DELETE FROM app_user WHERE
      obj.id = $1`
	res, err := tx.ExecContext(ctx, qry, id)
	if err != nil {
		return err
	}
	ra, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if ra == 0 {
		return fmt.Errorf("no rows affected")
	}
	if ra != 1 {
		return fmt.Errorf("invalid rows affected (%d)", ra)
	}
	if txNew {
		err = tx.Commit()
		if err != nil {
			return err
		}
	}
	return nil
}
