package main

const templ_model = `// Code generated by apigen. DO NOT EDIT.

package {{.Package}}

type {{.Name}} struct {
	{{range .Fields -}}
	{{.Name}}       {{.Type}}   {{.BT}}json:"{{.Field}}"{{.BT}}
	{{end}}
}

type {{.Name}}Field string

const (
	{{.Name}}Field_ID       {{.Name}}Field = "id"
	{{.Name}}Field_Email    {{.Name}}Field = "email"
	{{.Name}}Field_Name     {{.Name}}Field = "name"
	{{.Name}}Field_Salt     {{.Name}}Field = "salt"
	{{.Name}}Field_Password {{.Name}}Field = "password"
	{{.Name}}Field_Token    {{.Name}}Field = "token"
)

type {{.Name}}Sort struct {
	Field {{.Name}}Field ` + "`" + `json:"field"` + "`" + `
	Dir   SortDir   ` + "`" + `json:"dir"` + "`" + `
}

type {{.Name}}Filter struct {
	Field {{.Name}}Field ` + "`" + `json:"field"` + "`" + `
	Op    FilterOp  ` + "`" + `json:"op"` + "`" + `
	Value string    ` + "`" + `json:"value"` + "`" + `
}`
