-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-09-25T21:02:30+07:00

CREATE TABLE IF NOT EXISTS app_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255),
    version INTEGER,
    name VARCHAR(255),
    salt VARCHAR(255),
    password VARCHAR(255),
    token VARCHAR(255),
    created_by INTEGER,
    created_at DATETIME,
    updated_by INTEGER,
    updated_at DATETIME,
    FOREIGN KEY(created_by) REFERENCES app_user(id),
    FOREIGN KEY(updated_by) REFERENCES app_user(id)
);
