-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-10-06T12:48:38+07:00

CREATE TABLE app_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) NOT NULL ,
    version INTEGER NOT NULL ,
    name VARCHAR(255) NOT NULL ,
    password VARCHAR(2000) NOT NULL ,
    token VARCHAR(2000),
    created_by INTEGER,
    created_at DATETIME NOT NULL ,
    updated_by INTEGER,
    updated_at DATETIME NOT NULL ,
    FOREIGN KEY(created_by) REFERENCES app_user(id),
    FOREIGN KEY(updated_by) REFERENCES app_user(id)
);
