-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-10-06T19:11:40+07:00

CREATE TABLE app_role (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL ,
    description VARCHAR(255),
    privileges json NOT NULL 
);
