-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-10-06T12:48:38+07:00

CREATE TABLE charges (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(255) NOT NULL ,
    group VARCHAR(255),
    acq_gl_number VARCHAR(255),
    acq_fee INTEGER,
    switch_gl_number INTEGER,
    switch_fee INTEGER,
    benef_gl_number INTEGER,
    benef_fee INTEGER,
    add1GlNumber INTEGER,
    add1_fee INTEGER,
    add2_gl_number INTEGER,
    add2_fee INTEGER,
    description VARCHAR(255),
    modified_by VARCHAR(255) NOT NULL ,
    modified_date DATETIME NOT NULL 
);
