-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-10-06T12:48:38+07:00

CREATE TABLE gl_account (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(255) NOT NULL ,
    value VARCHAR(255),
    description VARCHAR(255),
    modified_by VARCHAR(255) NOT NULL ,
    modified_date DATETIME
);
