-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-09-26T13:49:40+07:00


CREATE TABLE IF NOT EXISTS app_user_role (
    app_user INTEGER,
    app_role INTEGER,
    FOREIGN KEY (app_user) REFERENCES app_user (id),
    FOREIGN KEY (app_role) REFERENCES app_role (id)
);
