// Code generated by apigen. DO NOT EDIT.

package model

import (
	"database/sql"
	"encoding/json"
)

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RoleField string

const (
	RoleField_ID          RoleField = "id"
	RoleField_Name        RoleField = "name"
	RoleField_Description RoleField = "description"
)

type RoleSort struct {
	Field RoleField `json:"field"`
	Dir   SortDir   `json:"dir"`
}

type RoleFilter struct {
	Field RoleField       `json:"field"`
	Op    FilterOp        `json:"op"`
	Value json.RawMessage `json:"value"`
}
