// Code generated by apigen. DO NOT EDIT.

package model

type User struct {
	ID       int64   `json:"id"`
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Salt     string  `json:"salt"`
	Password string  `json:"password"`
	Token    *string `json:"token,omitempty"`
}

type UserSortFields string

const (
	User_ID    UserSortFields = "id"
	User_Email UserSortFields = "email"
	User_Name  UserSortFields = "name"
)

type UserSort struct {
	Field UserSortFields `json:"field"`
	Dir   SortDir        `json:"dir"`
}

type UserFilter struct {
	ID    IntFilter    `json:"id"`
	Email StringFilter `json:"email"`
	Name  StringFilter `json:"name"`
}
