// Code generated by apigen. DO NOT EDIT.

package model

import "database/sql"

type User struct {
	ID              int64          `json:"id"`
	Email           string         `json:"email"`
	Name            string         `json:"name"`
	Salt            string         `json:"salt"`
	Password        string         `json:"password"`
	Token           sql.NullString `json:"token"`
	CreatedBy       *User          `json:"created_by"`
	UpdatedBy       *User          `json:"updated_by"`
	refCreatedBy_ID sql.NullInt64
	refUpdatedBy_ID sql.NullInt64
}

type UserField string

const (
	UserField_ID        UserField = "id"
	UserField_Email     UserField = "email"
	UserField_Name      UserField = "name"
	UserField_Salt      UserField = "salt"
	UserField_Password  UserField = "password"
	UserField_Token     UserField = "token"
	UserField_CreatedBy UserField = "created_by"
	UserField_UpdatedBy UserField = "updated_by"
)

type UserSort struct {
	Field UserField `json:"field"`
	Dir   SortDir   `json:"dir"`
}

type UserFilter struct {
	Field UserField `json:"field"`
	Op    FilterOp  `json:"op"`
	Value string    `json:"value"`
}
